### ISSUE TITLE
NameError: name 'NoneType' is not defined

### ISSUE THREAD

**Issue by ivoidcat** [ChinaXiaoQin/dns_Speed_test#2]
114.114.114.115 www.baidu.com  响应时间：Traceback (most recent call last):
  File "/Users/zhigangyang/ODev/dns_Speed_test/Linux.py", line 27, in run
    ms = ms + int(m.group())
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhigangyang/ODev/dns_Speed_test/mian.py", line 23, in <module>
    Linux.run(dns_list, html_list)
  File "/Users/zhigangyang/ODev/dns_Speed_test/Linux.py", line 33, in run
    except NoneType as e:
NameError: name 'NoneType' is not defined

**Comment by HyperCherry** [comment]
正则表达式的问题，把`Linux.py`或者`Windows.py`中
```python
m = re.search('[1-9]\d*', z)
```
改成
```python
m = re.search('-?\d+(\.\d+)?', z)
```
就可以了
